In [1]:
import numpy as np
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [2]:
import numpy as np
arr=np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [4]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [5]:
a=np.array([1,2,3,4])
b=np.copy(a)
print(b)

[1 2 3 4]


In [6]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a=np.linspace(0,20,5)
a

array([ 0.,  5., 10., 15., 20.])

In [14]:
a=np.linspace(9,81,3)
a

array([ 9., 45., 81.])

In [18]:
a=np.arange(12,21).reshape((3,3))
b=np.ones((3,3))
print(np.dot(a,b))

[[39. 39. 39.]
 [48. 48. 48.]
 [57. 57. 57.]]


In [19]:
a=np.sqrt([25,36,49])
a

array([5., 6., 7.])

In [4]:
import numpy as np
a=np.empty((5,3))
b=np.empty((3,2))
print(a)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1.16820622e-307 4.22792892e-307]
 [1.89144519e-307 4.22784744e-307]
 [1.06810336e-306 1.33511562e-306]]


In [8]:
a=np.append(np.array[[1,2,3],[6,7,8],[11,12,13],[4,5,9],[10,14,15]], axis=0)
b=np.append(np.array[[1,2],[4,5],[7,8]], axis=0)
print(a)
print(b)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [16]:
import numpy as np
a=np.empty((5,3))
a=np.append(np.array[[1,2,3],[6,7,8],[11,12,13],[4,5,9],[10,14,15]])
print(a)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [24]:
import numpy as np
a=np.random.random((5,3))
print("5*3  matrix")
print("-------------------------------")
print(a)
b=np.random.random((3,2))
print("3*2  matrix ")
print("------------------------------")
print(b)
c=np.dot(a,b)
print(" full matrix")
print("---------------------------")
print(c)

5*3  matrix
-------------------------------
[[0.86769591 0.22542464 0.53891121]
 [0.68192805 0.8154112  0.28963106]
 [0.0949021  0.00529263 0.65858843]
 [0.84697756 0.09442559 0.26958294]
 [0.22275168 0.03234802 0.91411911]]
3*2  matrix 
------------------------------
[[0.7114546  0.60137913]
 [0.23441945 0.80465879]
 [0.63671382 0.28430166]]
 full matrix
---------------------------
[[1.01330238 0.85641748]
 [0.86072119 1.14856768]
 [0.48809158 0.24856869]
 [0.79636846 0.66197789]
 [0.74809299 0.41987292]]


In [28]:
a=np.random.random((2,2))
a

array([[0.88032267, 0.03460392],
       [0.55310039, 0.85941064]])

In [ ]:
import numpy as np
first_array=np.array
a=np.random.random((5,3))
print("5*3  matrix")
print("-------------------------------")
print(a)
b=np.random.random((3,2))
print("3*2  matrix ")
print("------------------------------")
print(b)
c=np.dot(a,b)
print(" full matrix")
print("---------------------------")
print(c)