# numpy

numpy is a general purpose array-proccessing package, it provides a  high performnce multi-dimentional array object and tools for working with these arrays. it is fundamental package for scientific computing for python  

# what is array

an array is a data structure that stores value of same datatype . in python ,this is the main difference between array and list ,while python list can contain value corresponding to differet data types ,arrays in python can only contain value of corresponding to same data type.

In [ ]:
list=[1,2,3,4,5]

In [ ]:
np.

In [6]:
import numpy as np

In [7]:
my_list=[1,2,3,4]
arr=np.array(my_list)

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr

array([1, 2, 3, 4])

In [10]:
arr.shape

(4,)

In [11]:
lis=[1,2,3,4]
lis2=[6,7,8,9]
lis3=[11,12,13,14]
arr=np.array([lis,lis2,lis3])
print(arr)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]


In [12]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  6,  7],
       [ 8,  9, 11, 12, 13, 14]])

In [13]:
arr.shape

(3, 4)

# index


In [14]:
lis1=[10,20,30]
lis2=[40,50,60]
lis3=[70,80,90]
arr=np.array([lis1,lis2,lis3])
arr[1:,2:]

array([[60],
       [90]])

In [15]:
arr=np.arange(0,10)


In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [18]:
# copy and broadcasting
arr[5:]=100

In [19]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [20]:
arr1=arr

In [21]:
arr1[5:]=500
arr1

array([  0,   1,   2,   3,   4, 500, 500, 500, 500, 500])

In [22]:
arr1=arr.copy()

In [23]:
print(arr)
arr1[5:]=1000
print(arr1)

[  0   1   2   3   4 500 500 500 500 500]
[   0    1    2    3    4 1000 1000 1000 1000 1000]


In [24]:
#some conditional very useful in data analysis
val=2
arr*val

array([   0,    2,    4,    6,    8, 1000, 1000, 1000, 1000, 1000])

In [25]:
arr/2

array([  0. ,   0.5,   1. ,   1.5,   2. , 250. , 250. , 250. , 250. ,
       250. ])

In [26]:
arr%2

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0], dtype=int32)

In [27]:
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [28]:
arr[arr<2]

array([0, 1])

In [29]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [30]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.random.rand(2,3)

array([[0.59698662, 0.57366554, 0.13393687],
       [0.94697746, 0.13055847, 0.99796364]])

In [32]:
arr_ex=np.random.randn(4,4)
arr_ex

array([[-0.86390342,  1.1154587 , -0.59512672,  0.57918615],
       [-0.31935204,  1.20473492, -1.78014558, -0.78481957],
       [-0.18430339,  1.2767717 , -1.4553043 , -0.19197061],
       [-0.21482353, -0.57693513, -1.55618493,  0.73608947]])

In [33]:
np.dot(arr_ex,arr)

ValueError: shapes (4,4) and (10,) not aligned: 4 (dim 1) != 10 (dim 0)